=== momi97/ProjekatIST/projekatDTD.dtd
<?xml version = "1.0" encoding = "utf-8"?>

<!ELEMENT Adresar (Osoba,Kompanija)+>
<!ELEMENT Osoba (PunoIme,DatumRodjenja,Adresa,Telefon,Email+)>
<!ELEMENT Kompanija (ImeKompanije,Adresa,Telefon,Email)>
<!ELEMENT PunoIme (Ime,SrednjeIme?,Prezime+)>
<!ELEMENT Ime (#PCDATA)>
<!ELEMENT SrednjeIme (#PCDATA)>
<!ELEMENT Prezime (#PCDATA)>
<!ELEMENT DatumRodjenja (Dan,Mesec,Godina)>
<!ELEMENT Dan (#PCDATA)>
<!ELEMENT Mesec (#PCDATA)>
<!ELEMENT Godina (#PCDATA)>
<!ELEMENT Adresa (Ulica,Broj,Grad,Drzava?)>
<!ELEMENT Ulica (#PCDATA) >
<!ELEMENT Broj (#PCDATA)>
<!ELEMENT Grad (#PCDATA)>
<!ELEMENT Drzava (#PCDATA)>
<!ELEMENT Telefon (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT ImeKompanije (#PCDATA)>
<!ATTLIST Osoba Id ID #REQUIRED>
<!ATTLIST Adresa tip (stalna | privremena) "privremena">
<!ATTLIST Telefon tip (mobilni|fiksni) #REQUIRED>
<!ATTLIST Email tip (privatni|sluzbeni) #IMPLIED>

=== momi97/ProjekatIST/projekat.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Adresar SYSTEM "ProjekatDTD.dtd">

<Adresar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ProjekatSchema.xsd">
  
  <Osoba Id="1" >
    <PunoIme>
      <Ime>Nikola</Ime>
      <Prezime>Momic</Prezime>
      
    </PunoIme>
    <DatumRodjenja>
      <Dan>31</Dan>
    <Mesec>07</Mesec>
    <Godina>1997</Godina>
    </DatumRodjenja>
    <Adresa tip="Stalna">
      <Ulica>Visegradska</Ulica>
    <Broj>7</Broj>
    <Grad>Beograd</Grad>
    </Adresa>
    <Telefon tip="Mobilni">062/631-463</Telefon>
    <Email tipEmaila="Privatna">momic@gmail.com</Email>
     <Email tipEmaila="Sluzbena" >momicc@gmail.com</Email>
    <Email tipEmaila="Sluzbena" >momiccc@gmail.com</Email>

  </Osoba>
    <Osoba Id="2" >
    <PunoIme>
      <Ime>Marija</Ime>
      <SrednjeIme>Branko</SrednjeIme>
      <Prezime>Momic</Prezime>
      
      
    </PunoIme>
    <DatumRodjenja>
      <Dan>31</Dan>
    <Mesec>07</Mesec>
    <Godina>1994</Godina>
    </DatumRodjenja>
    <Adresa tip="Stalna">
      <Ulica>Visegradska</Ulica>
    <Broj>7</Broj>
    <Grad>Beograd</Grad>
    </Adresa>
    <Telefon tip="Mobilni">069/310-797</Telefon>
    <Email tipEmaila="Privatna">momic@gmail.com</Email>
     <Email tipEmaila="Privatna">momica@gmail.com</Email>
    <Email tipEmaila="Sluzbena" >momics@gmail.com</Email>
  </Osoba>
    <Osoba Id="3" >
    <PunoIme>
      <Ime>Uros</Ime>
      <SrednjeIme>Branko</SrednjeIme>
      <Prezime>Momic</Prezime>
      
      
    </PunoIme>
    <DatumRodjenja>
      <Dan>14</Dan>
    <Mesec>11</Mesec>
    <Godina>1995</Godina>
    </DatumRodjenja>
    <Adresa tip="Stalna">
      <Ulica>Visegradska</Ulica>
    <Broj>7</Broj>
    <Grad>Beograd</Grad>
    </Adresa>
    <Telefon tip="Mobilni">062/630-963</Telefon>
    <Email tipEmaila="Privatna">momic@gmail.com</Email>

  </Osoba>
  <Kompanija Id="1">
    <ImeKompanije>BBC</ImeKompanije>
  <Adresa tip="Stalna">
    <Ulica>Bulevar Oslobodjenja</Ulica>
  <Broj>10</Broj>
  <Grad>Beograd</Grad>
  </Adresa>
  <Telefon tip="Fiksni">050/205-592</Telefon>
  <Email tipEmaila="Privatna">nikola@gmail.com</Email>
  <Email tipEmaila="Sluzbena" >momicc@gmail.com</Email>
<Email tipEmaila="Sluzbena" >momara@gmail.com</Email>
  </Kompanija>
  <Kompanija Id="2">
    <ImeKompanije>Microsoft</ImeKompanije>
  <Adresa tip="Stalna">
    <Ulica>Jurija Gagarina</Ulica>
  <Broj>10</Broj>
  <Grad>Beograd</Grad>
  </Adresa>
  <Telefon tip="Fiksni">555/333-661</Telefon>
  <Email tipEmaila="Privatna">nikola@gmail.com</Email>
  <Email tipEmaila="Sluzbena" >momic@gmail.com</Email>
<Email tipEmaila="Sluzbena" >momara@gmail.com</Email>
  </Kompanija>
  <Kompanija Id="3">
    <ImeKompanije>Sony</ImeKompanije>
    <Adresa tip="Stalna">
      <Ulica>Jurija Gagarina</Ulica>
      <Broj>128</Broj>
      <Grad>Beograd</Grad>
    </Adresa>
    <Telefon tip="Fiksni">421/213-321</Telefon>
    <Email tipEmaila="Privatna">nikola@gmail.com</Email>
    <Email tipEmaila="Sluzbena" >momic@gmail.com</Email>
    <Email tipEmaila="Sluzbena" >momara@gmail.com</Email>
  </Kompanija>
</Adresar>
